### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by mnapthine** [action-is-hope/shelley#65]
Implement progress bar in Shelley:
- https://react-spectrum.adobe.com/react-aria/useProgressBar.html

Spectrum example:
https://react-spectrum.adobe.com/react-spectrum/ProgressBar.html

**Comment by cristinallamas** [comment]
> snyk-bot being weird, reopening.

I read skynet bot, and I thought ...
![](https://media.giphy.com/media/IZY2SE2JmPgFG/giphy.gif)
